server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: codej625
    password: '0625'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create