spring:
  application:
    name: domain-pattern-model
  datasource:
    url: jdbc:postgresql://localhost:5432/dev  # 데이터베이스 URL
    username: codej625           # 데이터베이스 사용자명
    password: '0625'            # 데이터베이스 비밀번호
    driver-class-name: org.postgresql.Driver             # PostgreSQL 드라이버 클래스
    hikari:
      maximum-pool-size: 10                                # 커넥션 풀 크기 (옵션)
      minimum-idle: 5                                      # 최소 커넥션 풀 크기 (옵션)
  jpa:
    hibernate:
      ddl-auto: create                                     # 데이터베이스 스키마 자동 업데이트 (none, update, create, create-drop 등)
    show-sql: true                                          # SQL 로그 출력 여부 (개발 시 유용)
logging:
  level:
    org.hibernate.orm.connections.pooling: off # 커넥션 풀 관련 로깅을 OFF로 설정